name: powercoders-ai
channels:
  - conda-forge
dependencies:
- python=3.6
- jupyterlab=0.35
- notebook=5.7
- tensorflow=1.12
- scikit-learn=0.21
- pandas=0.24
- requests=2.22
- beautifulsoup4=4.7
- matplotlib=3.1
- numpy=1.16
- pip
- pip:
  - tensorflowjs